name: main

on:
  push:
    branches: [master]
    tags:
  pull_request:

jobs:
  main:
    strategy:
      matrix:
        include:
        # linux
        - os: ubuntu-latest
          python: pypy-3.7
          toxenv: py
        - os: ubuntu-latest
          python: 2.7
          toxenv: py
        - os: ubuntu-latest
          python: 3.6
          toxenv: py
        - os: ubuntu-latest
          python: 3.7
          toxenv: py
        - os: ubuntu-latest
          python: 3.8
          toxenv: py
        - os: ubuntu-latest
          python: 3.9
          toxenv: py
        # windows
        - os: windows-latest
          python: 3.6
          toxenv: py
        # misc
        - os: ubuntu-latest
          python: 2.7
          toxenv: flake8
        - os: ubuntu-latest
          python: 3.9
          toxenv: flake8
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - run: python -mpip install --upgrade pip tox virtualenv
    - run: tox -e ${{ matrix.toxenv }}
    - name: Codecov coverage report upload
      uses: codecov/codecov-action@v1
      if: ${{ matrix.toxenv == 'py' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        flags: ${{ matrix.os }}${{ matrix.python }}
        name: xlorm-tests
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
